# Generated by Django 2.2.6 on 2019-12-02 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleHealthKitUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(help_text='The upload binary file.', upload_to='uploads/%Y/%m/%d/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apple Healthkit Upload',
                'verbose_name_plural': 'Apple Healthkit Uploads',
                'db_table': 'biodb_apple_health_kit_uploads',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
