# Generated by Django 2.2.7 on 2019-12-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applehealthkitdatadb',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
