# Generated by Django 2.2.7 on 2019-12-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applehealthkitdatadb',
            name='value',
            field=models.FloatField(),
        ),
    ]
