from api.serializers.uploads.upload_serializer import AppleHealthKitUploadSerializer
from api.serializers.gateway.register_serializer import RegisterSerializer
from api.serializers.dashboard.list_serializer import ListSerializer
from api.serializers.dashboard.update_user_serializer import UpdateSerializer
from api.serializers.uploads.list_upload_serializer import ListUploadSerializer
from api.serializers.dashboard.sensor_details_serializer import TimeSeriesDataSerializer
